[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build]
base = "."
command = "npm run build"
publish = "./build/"

[build.environment]
REACT_APP_API_URL = "https://desafio-pokemon-store.netlify.app/"